### ISSUE TITLE
Add ability to set Ocp-Apim-Subscription-Region

### ISSUE THREAD

**Issue by eckleyval** [tomahg/Gulla.EpiserverAutomaticImageDescription#2]
This could be me with my Azure Translate setup, but it seems I need to send **Ocp-Apim-Subscription-Region** to get the translation to work.  Can the region be added as an app setting, and added to the header of the request?

[https://docs.microsoft.com/en-us/azure/cognitive-services/translator/quickstart-translator?tabs=csharp]

Thanks

**Comment by tomahg** [comment]
Hi, @eckleyval - thank you for taking your time to register this issue.

I have added support for setting **Ocp-Apim-Subscription-Region**, just use the app setting:
`Gulla.Episerver.AutomaticImageDescription:Translator.SubscriptionRegion`

This is included in the new release 1.4.0 just uploaded a few minutes ago. The package is published at nuget.org just now, and will be published at nuget.episerver.com as soon as its manually approved.

Let me know if this works according to your expectations, and I'll update the documentation.
Thanks.

**Comment by eckleyval** [comment]
Awesome! I got it to work :) 

Great job on this plug-in. I saw your presentation you did on this with the Oslo group a few months ago and knew this was exactly what I needed for my epi site. I'm happy to finally be able to implement it.

**Comment by tomahg** [comment]
Great! 😃
